resolver: lts-5.2
extra-deps:
  - bytestring-tree-builder-0.2.4
  - hasql-0.19.6
  - hasql-transaction-0.4.2
  - Ranged-sets-0.3.0
  - packdeps-0.4.2.1
  - postgresql-error-codes-1
ghc-options:
  postgrest: -O2 -Werror -Wall -fwarn-monomorphism-restriction -fwarn-missing-exported-sigs -fwarn-identities

packages:
- '.'
